-- LV-Seed v2  Leuschner · 11.6.2026
-- 395 Arbeitspositionen → 214 Cluster
-- Neue Spalten price_min / price_max + Kategorien UMZ / SON
--
ALTER TABLE lv_positions
  ADD COLUMN IF NOT EXISTS price_min NUMERIC,
  ADD COLUMN IF NOT EXISTS price_max NUMERIC;

DO $$
DECLARE cid UUID;
BEGIN
  SELECT id INTO cid FROM companies ORDER BY created_at LIMIT 1;
  INSERT INTO lv_positions
    (id, company_id, cat, name, price, price_min, price_max, unit, short_text, long_text, zulagen)
  VALUES
    ('ERD-100', cid, 'ERD', 'Bagger und Radladerarbeiten', 55, 55, 60, NULL, NULL, NULL, '{}'),
    ('ERD-101', cid, 'ERD', 'Brechsand verteilen und Verdichten', 55, 45, 60, NULL, NULL, NULL, '{}'),
    ('ERD-102', cid, 'ERD', 'Entsorgung', 20, 10, 45, NULL, NULL, NULL, '{}'),
    ('ERD-103', cid, 'ERD', 'Schotter verteilen und Verdichten', 60, 55, 65, NULL, NULL, NULL, '{}'),
    ('ERD-104', cid, 'ERD', 'Füllsand verteilen und Verdichten', 55, 50, 60, NULL, NULL, NULL, '{}'),
    ('ERD-105', cid, 'ERD', 'Entsorgung Bauschutt', 25, 20, 397.9, NULL, NULL, NULL, '{}'),
    ('ERD-106', cid, 'ERD', 'Rohre Ausgerichtet und Angeschlossen', 55, 45, 55, NULL, NULL, NULL, '{}'),
    ('ERD-107', cid, 'ERD', 'Aco Drain Rinne in Beton setzen und anschließen', 55, 47.5, 55, NULL, NULL, NULL, '{}'),
    ('ERD-108', cid, 'ERD', 'Mutterboden einbauen', 60, 55, 60, NULL, NULL, NULL, '{}'),
    ('ERD-109', cid, 'ERD', 'Fundament Herstellen', 40, 40, 55, NULL, NULL, NULL, '{}'),
    ('ERD-110', cid, 'ERD', 'Frachtkosten Fremd LKW', 19.5, 19.5, 19.5, NULL, NULL, NULL, '{}'),
    ('ERD-111', cid, 'ERD', 'Betonfundamente entfernen', 47.5, 47.5, 47.5, NULL, NULL, NULL, '{}'),
    ('ERD-112', cid, 'ERD', 'Grabaushub / 2Mitarbeiter', 50, 50, 90, NULL, NULL, NULL, '{}'),
    ('ERD-113', cid, 'ERD', 'Entwässerung Herstellen in Kg Rohr + Ablauf', 60, 45, 60, NULL, NULL, NULL, '{}'),
    ('ERD-114', cid, 'ERD', 'Verdichten', 50, 48, 55, NULL, NULL, NULL, '{}'),
    ('ERD-115', cid, 'ERD', 'Kabelverlegearbeiten', 50, 50, 50, NULL, NULL, NULL, '{}'),
    ('ERD-116', cid, 'ERD', 'Kiesbeet Zurückgebaut', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('ERD-117', cid, 'ERD', 'Entsorgungskosten Betonfundamente mit stahleinlage', NULL, NULL, NULL, NULL, NULL, NULL, '{}'),
    ('ERD-118', cid, 'ERD', 'Fundament erstellt für Gartenmauer', NULL, NULL, NULL, NULL, NULL, NULL, '{}'),
    ('ERD-119', cid, 'ERD', 'Zusatzarbeit: Drainage erstellen', NULL, NULL, NULL, NULL, NULL, NULL, '{}'),
    ('ERD-120', cid, 'ERD', 'Rohrverstopfung Lokalisiert', 50, 50, 55, NULL, NULL, NULL, '{}'),
    ('ERD-121', cid, 'ERD', 'Zusatzarbeit: Rohre umgelegt', NULL, NULL, NULL, NULL, NULL, NULL, '{}'),
    ('ERD-122', cid, 'ERD', 'Vlies Verlegen', 60, 45, 60, NULL, NULL, NULL, '{}'),
    ('ERD-123', cid, 'ERD', 'Grabaushub / " Mitarbeiter', 90, 90, 90, NULL, NULL, NULL, '{}'),
    ('ERD-124', cid, 'ERD', 'Wasser Abpumpen', 45, 45, 45, NULL, NULL, NULL, '{}'),
    ('ERD-125', cid, 'ERD', 'Pumparbeiten', 45, 45, 45, NULL, NULL, NULL, '{}'),
    ('ERD-126', cid, 'ERD', 'Abwasserschacht setzen', 50, 50, 50, NULL, NULL, NULL, '{}'),
    ('ERD-127', cid, 'ERD', 'Gruben Geschlossen und verdichtet', 45, 45, 45, NULL, NULL, NULL, '{}'),
    ('ERD-128', cid, 'ERD', 'Stufe abbrechen und neu verkleben', 47.5, 47.5, 47.5, NULL, NULL, NULL, '{}'),
    ('ERD-129', cid, 'ERD', 'Fallrohre instandgesetzt', 45, 45, 45, NULL, NULL, NULL, '{}'),
    ('ERD-130', cid, 'ERD', 'L Borte setzen', 45, 45, 45, NULL, NULL, NULL, '{}'),
    ('ERD-131', cid, 'ERD', 'Stufe Herstellen (Mauern od. Kleben', 48, 48, 48, NULL, NULL, NULL, '{}'),
    ('ERD-132', cid, 'ERD', 'Mehraufwand L Borte', 48, 48, 48, NULL, NULL, NULL, '{}'),
    ('ERD-133', cid, 'ERD', 'Fundamente Für Carport Herstellen', 48, 48, 48, NULL, NULL, NULL, '{}'),
    ('ERD-134', cid, 'ERD', 'Stufe erstellen in beton', 48, 48, 48, NULL, NULL, NULL, '{}'),
    ('ERD-135', cid, 'ERD', 'Borte setzen in Beton', 48, 48, 48, NULL, NULL, NULL, '{}'),
    ('ERD-136', cid, 'ERD', 'Entsorgung Steinabfall', 120, 120, 120, NULL, NULL, NULL, '{}'),
    ('ERD-137', cid, 'ERD', 'sand entsorgen', 30, 30, 30, NULL, NULL, NULL, '{}'),
    ('ERD-138', cid, 'ERD', 'Baggerarbeit', 60, 60, 60, NULL, NULL, NULL, '{}'),
    ('ERD-139', cid, 'ERD', 'Weg verfüllen und verdichten', 60, 60, 60, NULL, NULL, NULL, '{}'),
    ('ERD-140', cid, 'ERD', 'Stufe entfernen', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('ERD-141', cid, 'ERD', 'Einspülen und ansähen', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('ERD-142', cid, 'ERD', 'auskoffern', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('ERD-143', cid, 'ERD', 'Parkplatz herstellen', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('ERD-144', cid, 'ERD', 'Fläche einebnen und auffüllen', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('ERD-145', cid, 'ERD', 'Aco Drain Rinne einbauen und anschließen', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('ERD-146', cid, 'ERD', 'Kabelkanäle in Beton geflext und Gestämmt', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('ERD-147', cid, 'ERD', 'Hofablauf unter Wasserhahn Hergestellt und an Gitterrost angepasst', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('ERD-148', cid, 'ERD', 'Rohr Freigestämmt in Schacht, Verrohrung hergestellt, lagenweise Verdichtet und Hofablauf angeschlossen', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('ERD-149', cid, 'ERD', 'Grasnabe Durchgefräst, Mutterboden Angefüllt,Angeglichen und Eingesäht', 800, 800, 800, NULL, NULL, NULL, '{}'),
    ('ERD-150', cid, 'ERD', 'Noppenbahn Anbringen', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('ERD-151', cid, 'ERD', 'Defekten Regenwasserablauf instandgesetzt', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('ERD-152', cid, 'ERD', 'Entsorgungskosten Sondermüll Rigips', 150, 150, 150, NULL, NULL, NULL, '{}'),
    ('ERD-153', cid, 'ERD', '2 Abwasserschächte instandgesetzt', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('ERD-154', cid, 'ERD', 'Regenwasserschacht saniert und mit Beton vergossen, vorhandenen Deckel neu Aufgesetzt', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('ERD-155', cid, 'ERD', 'Neuen Schacht Eingebaut', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('ERD-156', cid, 'ERD', 'L Steine Gesetzt', 60, 60, 60, NULL, NULL, NULL, '{}'),
    ('ERD-157', cid, 'ERD', 'Kellerschacht zurückbauen', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('ERD-158', cid, 'ERD', 'Neuen Kellerschacht Montieren', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('ERD-159', cid, 'ERD', 'Fallrohr eingebaut', 60, 60, 60, NULL, NULL, NULL, '{}'),
    ('ERD-160', cid, 'ERD', 'Kanalschacht verschließen, rohre absanden', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('ERD-161', cid, 'ERD', 'Hochbeet erstellen', 60, 60, 60, NULL, NULL, NULL, '{}'),
    ('ERD-162', cid, 'ERD', 'Mehrarbeit Boden Auskoffern', 60, 60, 60, NULL, NULL, NULL, '{}'),
    ('ERD-163', cid, 'ERD', 'Container Erdaushub Lehmhaltiger Mischboden', 290, 290, 290, NULL, NULL, NULL, '{}'),
    ('ERD-164', cid, 'ERD', 'Zusatzarbeit: Stufe entfernt', 60, 60, 60, NULL, NULL, NULL, '{}'),
    ('ERD-165', cid, 'ERD', 'Zusatzarbeit: Gefälle verändern für Schmutzwasserschacht', 60, 60, 60, NULL, NULL, NULL, '{}'),
    ('ERD-166', cid, 'ERD', 'Zusatzarbeit: Stemmarbeiten', 60, 60, 60, NULL, NULL, NULL, '{}'),
    ('ERD-167', cid, 'ERD', 'Entsorgung Eternit', 97.48, 97.48, 97.48, NULL, NULL, NULL, '{}'),
    ('ERD-168', cid, 'ERD', 'Geschätze kosten zur Asbest entsorgung', 243.7, 243.7, 243.7, NULL, NULL, NULL, '{}'),
    ('ERD-169', cid, 'ERD', 'Stützenfuß auf Beton M 20 Höhe 310 mm höhenverstellbar, feuerverzinkt', 25.28, 25.28, 25.28, NULL, NULL, NULL, '{}'),
    ('ERD-170', cid, 'ERD', 'Rohrgraben Hergestellt', 60, 60, 60, NULL, NULL, NULL, '{}'),
    ('ERD-171', cid, 'ERD', 'Zusatzarbeit: Stemmarbeiten Fundament', 30, 30, 30, NULL, NULL, NULL, '{}'),
    ('ERD-172', cid, 'ERD', 'Hofablauf einbauen', 60, 60, 60, NULL, NULL, NULL, '{}'),
    ('ERD-173', cid, 'ERD', 'Steine Aufgenommen und Abtransportiert', 60, 60, 60, NULL, NULL, NULL, '{}'),
    ('ERD-174', cid, 'ERD', 'Stufe neu verfugen', 60, 60, 60, NULL, NULL, NULL, '{}'),
    ('PFL-100', cid, 'PFL', 'Pflasterarbeiten', 60, 45, 60, NULL, NULL, NULL, '{}'),
    ('PFL-101', cid, 'PFL', 'Rütteln, schneiden und einschlämmen', 48, 47.5, 60, NULL, NULL, NULL, '{}'),
    ('PFL-102', cid, 'PFL', 'Borde setzen in Beton', 55, 45, 60, NULL, NULL, NULL, '{}'),
    ('PFL-103', cid, 'PFL', 'Pflasterung aufnehmen und Rückbau', 57.5, 48, 57.5, NULL, NULL, NULL, '{}'),
    ('PFL-104', cid, 'PFL', 'Zusatzarbeit: Steine u. Platten aufgenommen', NULL, NULL, NULL, NULL, NULL, NULL, '{}'),
    ('PFL-105', cid, 'PFL', 'Demontage Terrasse', 55, 48, 55, NULL, NULL, NULL, '{}'),
    ('PFL-106', cid, 'PFL', 'Bordsteine entfernen', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('PFL-107', cid, 'PFL', 'Steine u. Platten aufgenommen', 45, 45, 45, NULL, NULL, NULL, '{}'),
    ('PFL-108', cid, 'PFL', 'Planung f. Rasenbord herstellen', 48, 48, 48, NULL, NULL, NULL, '{}'),
    ('PFL-109', cid, 'PFL', 'Terrrassenplatten Verlegen', 47.5, 47.5, 47.5, NULL, NULL, NULL, '{}'),
    ('PFL-110', cid, 'PFL', 'Pflasterplanung erstellen', 50, 50, 50, NULL, NULL, NULL, '{}'),
    ('PFL-111', cid, 'PFL', 'Pflastersteine aufgenommen und Rohr freigelegt', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('PFL-112', cid, 'PFL', 'Pflastern (Klinker+ zierstreifen', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('PFL-113', cid, 'PFL', 'Pflaster aufnehmen und säubern', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('PFL-114', cid, 'PFL', 'Terrassenplatten einbauen', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('PFL-115', cid, 'PFL', 'Graben verfüllen und Pflasterung wiederherstellen', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('PFL-116', cid, 'PFL', 'Blumenbeet zurückgebaut und verkleinert, Randbefestigung in Naturstein Gesetzt', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('PFL-117', cid, 'PFL', 'Schadhafte stellen mit Beton ausgeglichen und Randbefestigung zu den Platten hergestellt', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('PFL-118', cid, 'PFL', 'Carport +60cm Verbreitern und Lichtplatten Befestigen', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('PFL-119', cid, 'PFL', 'Sandwichplatten Montieren und Verschrauben', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('PFL-120', cid, 'PFL', 'Betonplatten Ausbaggern', 60, 60, 60, NULL, NULL, NULL, '{}'),
    ('PFL-121', cid, 'PFL', 'Beet ausbaggern und für Pflasterfläche vorbereiten', 60, 60, 60, NULL, NULL, NULL, '{}'),
    ('PFL-122', cid, 'PFL', 'Steine u. Bordsteine aufgenommen', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('PFL-123', cid, 'PFL', 'Zusatzarbeit: Pflasterung aufgenommen und tiefer ausgekoffert', 60, 60, 60, NULL, NULL, NULL, '{}'),
    ('PFL-124', cid, 'PFL', 'Zusatzarbeit: Platten vom Nachbargrundstück mit angehoben auf Kundenwunsch', 60, 60, 60, NULL, NULL, NULL, '{}'),
    ('PFL-125', cid, 'PFL', 'Plattenbag f. Asbesthaltige Abfälle', 14.23, 14.23, 14.23, NULL, NULL, NULL, '{}'),
    ('PFL-126', cid, 'PFL', 'Rohre Freigelegt, Erneuert, Bodenaustausch, Verdichtet und Gepflastert', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('PFL-127', cid, 'PFL', 'Plattensack 30 cm Big Bag für Asbestentsorgung Asbestsymbol-Druck 2-farbig Umlaufende Schürze mit Schnürbandbefestigung SF 5:1 SWL: 1.500 kg', 12, 12, 12, NULL, NULL, NULL, '{}'),
    ('GTN-100', cid, 'GTN', 'Grünabfall Entsorgung', 125, 20, 125, NULL, NULL, NULL, '{}'),
    ('GTN-101', cid, 'GTN', 'Baumwurzelfräsen', 53.27, 50, 180, NULL, NULL, NULL, '{}'),
    ('GTN-102', cid, 'GTN', 'Jahresrückschnitt Hecken / Büsche / Kl. Bäume', 45, 45, 4300, NULL, NULL, NULL, '{}'),
    ('GTN-103', cid, 'GTN', 'Hecke entfernen', 900, 47.5, 900, NULL, NULL, NULL, '{}'),
    ('GTN-104', cid, 'GTN', 'Rasenfläche angleichen', 60, 55, 60, NULL, NULL, NULL, '{}'),
    ('GTN-105', cid, 'GTN', 'Borte setzen', 45, 45, 55, NULL, NULL, NULL, '{}'),
    ('GTN-106', cid, 'GTN', 'Dachrinnenreinigung', 60, 55, 85, NULL, NULL, NULL, '{}'),
    ('GTN-107', cid, 'GTN', 'Baumschnitt', 55, 48, 55, NULL, NULL, NULL, '{}'),
    ('GTN-108', cid, 'GTN', 'Rindenmulch verteilen, Blätter entfernen und Vlies auslegen', 55, 50, 55, NULL, NULL, NULL, '{}'),
    ('GTN-109', cid, 'GTN', 'Rasengittersteine Verlegen', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('GTN-110', cid, 'GTN', 'Aufräumarbeiten', 42.5, 42.5, 42.5, NULL, NULL, NULL, '{}'),
    ('GTN-111', cid, 'GTN', 'Rasenbort setzen in Beton', 47.5, 47.5, 47.5, NULL, NULL, NULL, '{}'),
    ('GTN-112', cid, 'GTN', 'Baumstumpfentfernung incl. entsorgung', 320, 320, 320, NULL, NULL, NULL, '{}'),
    ('GTN-113', cid, 'GTN', 'Borte Setzen und Richten', 48, 48, 48, NULL, NULL, NULL, '{}'),
    ('GTN-114', cid, 'GTN', 'Kies verteilen und Kunstrasen Verlegen', 48, 48, 48, NULL, NULL, NULL, '{}'),
    ('GTN-115', cid, 'GTN', 'Dachrinnenhalter Versetzen', 45, 45, 45, NULL, NULL, NULL, '{}'),
    ('GTN-116', cid, 'GTN', 'Entfernung Efeu', 58, 58, 58, NULL, NULL, NULL, '{}'),
    ('GTN-117', cid, 'GTN', 'Grünflächen Mähen und Graben ausheben', 58, 58, 58, NULL, NULL, NULL, '{}'),
    ('GTN-118', cid, 'GTN', 'Grundstück einebnen incl. Wurzelfräsen', 3201.68067227, 3201.68, 3201.68, NULL, NULL, NULL, '{}'),
    ('GTN-119', cid, 'GTN', 'Abfallentsorgung', 2680.67226891, 2680.67, 2680.67, NULL, NULL, NULL, '{}'),
    ('GTN-120', cid, 'GTN', 'Pinienrinde verteilt', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('GTN-121', cid, 'GTN', 'Pflanzen Ausgebaggert, Rasenrollschicht ausgebessert', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('GTN-122', cid, 'GTN', 'weitere Hecke und Diverse Pflanzen Entfernen und Entsorgen', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('GTN-123', cid, 'GTN', 'Boden im Wurzelbereich verdichten, ebnen und ggf. Anfüllen', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('GTN-124', cid, 'GTN', 'Baum hinter Garage Gefällt', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('GTN-125', cid, 'GTN', 'Mähkanten eingebaut, rasenfläche abgeharkt, begradigt, angesäht und Pflanzen eingepflanzt', 60, 60, 60, NULL, NULL, NULL, '{}'),
    ('GTN-126', cid, 'GTN', 'Gartenarbeiten, Bestehend aus: Pflanzen umgepflanzt und telweise Entfernt, Unkraut entfernt, Bauschutt und Grünabfall aufgeladen und abgefahren', 45, 45, 45, NULL, NULL, NULL, '{}'),
    ('GTN-127', cid, 'GTN', 'Bäume gefällt', 60, 60, 60, NULL, NULL, NULL, '{}'),
    ('GTN-128', cid, 'GTN', 'Wildkraut entfernt', 60, 60, 60, NULL, NULL, NULL, '{}'),
    ('GTN-129', cid, 'GTN', 'Mäh und Aufräumarbeiten', 60, 60, 60, NULL, NULL, NULL, '{}'),
    ('GTN-130', cid, 'GTN', 'Mäharbeiten', 60, 60, 60, NULL, NULL, NULL, '{}'),
    ('ZAU-100', cid, 'ZAU', 'Doppelstabmattenzaun aufbauen', 60, 45, 60, NULL, NULL, NULL, '{}'),
    ('ZAU-101', cid, 'ZAU', 'Zaunfundamente herstellen', 60, 38, 60, NULL, NULL, NULL, '{}'),
    ('ZAU-102', cid, 'ZAU', 'Einfädeln von Sichtschutzstreifen', 55, 50, 60, NULL, NULL, NULL, '{}'),
    ('ZAU-103', cid, 'ZAU', 'Zaun zurück gebaut', 60, 60, 60, NULL, NULL, NULL, '{}'),
    ('ZAU-104', cid, 'ZAU', 'Zusatzarbeit: Pfostenträger ausheben und betonieren', NULL, NULL, NULL, NULL, NULL, NULL, '{}'),
    ('ZAU-105', cid, 'ZAU', 'Zaun demontage', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('ZAU-106', cid, 'ZAU', 'Zaun aufgestellt u. Tür gebaut', 38, 38, 38, NULL, NULL, NULL, '{}'),
    ('ZAU-107', cid, 'ZAU', 'Terassenüberdachung herstellen und anpassen', 42.5, 42.5, 42.5, NULL, NULL, NULL, '{}'),
    ('ZAU-108', cid, 'ZAU', 'Dach eingedeckt', 42.5, 42.5, 42.5, NULL, NULL, NULL, '{}'),
    ('ZAU-109', cid, 'ZAU', '7 Zaunpfosten in Beton setzen', 47.5, 47.5, 47.5, NULL, NULL, NULL, '{}'),
    ('ZAU-110', cid, 'ZAU', 'Stufe aus Palisaden Herstellen', 48, 48, 48, NULL, NULL, NULL, '{}'),
    ('ZAU-111', cid, 'ZAU', 'Carport pfeiler Abändern', 47.5, 47.5, 47.5, NULL, NULL, NULL, '{}'),
    ('ZAU-112', cid, 'ZAU', 'Boden im Zaunbereich verdichten', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('ZAU-113', cid, 'ZAU', '12 Pfosten betonieren + zaun aufstellen', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('ZAU-114', cid, 'ZAU', 'Entsorgung Alter Zaun', 60, 60, 60, NULL, NULL, NULL, '{}'),
    ('ZAU-115', cid, 'ZAU', 'Tor Herstellen und Abschließende Arbeiten', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('ZAU-116', cid, 'ZAU', 'Zusatzarbeit : Beton an Doppelstabmattenzaun Weggestämmt, Bordstein entfernt, Neues Bord gesetzt, Baumwurzel entfernt für Zaun', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('ZAU-117', cid, 'ZAU', 'Carport Aufbauen', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('ZAU-118', cid, 'ZAU', 'Platten Verlegen unter Zaun', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('ZAU-119', cid, 'ZAU', 'Blechdach demontieren und entsorgen', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('ZAU-120', cid, 'ZAU', 'Windfeder Montieren', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('ZAU-121', cid, 'ZAU', 'Aufbau Überdachung', 50, 50, 50, NULL, NULL, NULL, '{}'),
    ('ZAU-122', cid, 'ZAU', 'L Steine Gesetzt, Terrasse Gepflastert, Zaunpfosten mit einbetoniert', 57.5, 57.5, 57.5, NULL, NULL, NULL, '{}'),
    ('ZAU-123', cid, 'ZAU', 'Zaun Aufgebaut und Tür Erstellt', 57.5, 57.5, 57.5, NULL, NULL, NULL, '{}'),
    ('ZAU-124', cid, 'ZAU', 'Palisaden Gesetzt und Umrandung für Brunnen Hergestellt', 60, 60, 60, NULL, NULL, NULL, '{}'),
    ('ZAU-125', cid, 'ZAU', 'Doppelstabmattenzaun versetzen', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('ZAU-126', cid, 'ZAU', 'Ausheben und Betonieren der 3 Zusätzlichen Pfostenträger', 297.33, 297.33, 297.33, NULL, NULL, NULL, '{}'),
    ('ZAU-127', cid, 'ZAU', 'Pfostenträger 12x100 zum Einbetonieren', 12, 12, 12, NULL, NULL, NULL, '{}'),
    ('ZAU-128', cid, 'ZAU', 'Entsorgung Holzzaun', 30, 30, 30, NULL, NULL, NULL, '{}'),
    ('ZAU-129', cid, 'ZAU', 'Borde und Pfostenträger setzen in Beton', 60, 60, 60, NULL, NULL, NULL, '{}'),
    ('VWG-100', cid, 'VWG', 'Transportpauschale f. fertigbeton', 17.5, 17.5, 20, NULL, NULL, NULL, '{}'),
    ('VWG-101', cid, 'VWG', 'Anfahrtspauschale', 17.5, 15, 25, NULL, NULL, NULL, '{}'),
    ('VWG-102', cid, 'VWG', 'Arbeitslohn', 60, 50, 60, NULL, NULL, NULL, '{}'),
    ('VWG-103', cid, 'VWG', 'Einsatz Motorerdbohrer', 30, 30, 30, NULL, NULL, NULL, '{}'),
    ('VWG-104', cid, 'VWG', 'Frachtpauschale ab werk', 125, 15, 125, NULL, NULL, NULL, '{}'),
    ('VWG-105', cid, 'VWG', 'Baggergerätenutzung', 50, 50, 50, NULL, NULL, NULL, '{}'),
    ('VWG-106', cid, 'VWG', 'Europaletten anteilige Leihgebühr', 3.5, 3.5, 3.5, NULL, NULL, NULL, '{}'),
    ('VWG-107', cid, 'VWG', 'Abgesprochene Mehrarbeit', 60, 60, 350, NULL, NULL, NULL, '{}'),
    ('VWG-108', cid, 'VWG', 'Leihgebühr Microbagger', NULL, NULL, NULL, NULL, NULL, NULL, '{}'),
    ('VWG-109', cid, 'VWG', 'Container Stellpauschale Eilderts', NULL, NULL, NULL, NULL, NULL, NULL, '{}'),
    ('VWG-110', cid, 'VWG', 'Transportpauschale für Sand', 24.5, 20, 24.5, NULL, NULL, NULL, '{}'),
    ('VWG-111', cid, 'VWG', 'Wartezeit V.D.Pütten', 38, 38, 38, NULL, NULL, NULL, '{}'),
    ('VWG-112', cid, 'VWG', 'Baustelle einrichten', 48, 48, 48, NULL, NULL, NULL, '{}'),
    ('VWG-113', cid, 'VWG', 'Einsatz Spirale', 25, 25, 25, NULL, NULL, NULL, '{}'),
    ('VWG-114', cid, 'VWG', 'Einsatz Nassschneider', 60, 60, 60, NULL, NULL, NULL, '{}'),
    ('VWG-115', cid, 'VWG', 'Anfahrtspauschale > 50km', 50, 50, 50, NULL, NULL, NULL, '{}'),
    ('VWG-116', cid, 'VWG', 'Planung erstellen', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('VWG-117', cid, 'VWG', 'Verbrauchsmaterialpauschale', 50.42, 50.42, 50.42, NULL, NULL, NULL, '{}'),
    ('VWG-118', cid, 'VWG', 'Entsorgung Altes Pflaster und container stellpauschale', 604.8, 604.8, 604.8, NULL, NULL, NULL, '{}'),
    ('VWG-119', cid, 'VWG', 'Handwerkerkosten', 800, 800, 800, NULL, NULL, NULL, '{}'),
    ('VWG-120', cid, 'VWG', 'Leihgebühr Radlader', 148.8, 148.8, 148.8, NULL, NULL, NULL, '{}'),
    ('VWG-121', cid, 'VWG', 'Montagekosten', 1800, 1800, 1800, NULL, NULL, NULL, '{}'),
    ('VWG-122', cid, 'VWG', 'Arbeitsbühne Selbstfahrend Benzin', 159.66, 159.66, 159.66, NULL, NULL, NULL, '{}'),
    ('VWG-123', cid, 'VWG', 'Einsatz Motorpfahlramme', 139, 139, 139, NULL, NULL, NULL, '{}'),
    ('UMZ-001', cid, 'UMZ', 'Umzug', 2750, 50, 2750, NULL, NULL, NULL, '{}'),
    ('UMZ-002', cid, 'UMZ', 'Umzug von 26842 nach 06779', 1350, 1350, 1350, NULL, NULL, NULL, '{}'),
    ('UMZ-003', cid, 'UMZ', 'Umzug Bochum, 3 umzugshelfer auf- abbau', 3400, 3400, 3400, NULL, NULL, NULL, '{}'),
    ('UMZ-004', cid, 'UMZ', 'Umzug incl. Umzugshelfer auf und ab - bau', 780, 780, 780, NULL, NULL, NULL, '{}'),
    ('SON-001', cid, 'SON', 'Kabelverlegungsarbeiten', NULL, NULL, NULL, NULL, NULL, NULL, '{}'),
    ('SON-002', cid, 'SON', 'Ausbesserungsarbeiten', 55, 48, 55, NULL, NULL, NULL, '{}'),
    ('SON-003', cid, 'SON', 'Reinigungen von Boxen', 38, 38, 38, NULL, NULL, NULL, '{}'),
    ('SON-004', cid, 'SON', 'Hofentwässerung eingebaut', 45, 45, 45, NULL, NULL, NULL, '{}'),
    ('SON-005', cid, 'SON', 'Schneidarbeiten', 48, 48, 48, NULL, NULL, NULL, '{}'),
    ('SON-006', cid, 'SON', 'Rüttteln, schneiden und einschlämmen', 48, 48, 48, NULL, NULL, NULL, '{}'),
    ('SON-007', cid, 'SON', 'Fflasterarbeiten', 2800, 2800, 2800, NULL, NULL, NULL, '{}'),
    ('SON-008', cid, 'SON', 'Fugen ausgeflext und vorbereitet fürs Einfugen', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('SON-009', cid, 'SON', 'Herstellen von 19 Löchern', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('SON-010', cid, 'SON', 'Bauschutt entsorgen', 30, 30, 30, NULL, NULL, NULL, '{}'),
    ('SON-011', cid, 'SON', 'Kvh holzunterkonstuktion anpassen und Montieren', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('SON-012', cid, 'SON', 'Gemischte Bau und Abbruchabfälle', 169.75, 169.75, 169.75, NULL, NULL, NULL, '{}'),
    ('SON-013', cid, 'SON', 'Montageschaum', 7.55, 7.55, 7.55, NULL, NULL, NULL, '{}'),
    ('SON-014', cid, 'SON', 'Bodenverlegearbeiten', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('SON-015', cid, 'SON', 'Duschwand Hergestellt', 55, 55, 55, NULL, NULL, NULL, '{}'),
    ('SON-016', cid, 'SON', 'Abbruch der Rollschicht', 60, 60, 60, NULL, NULL, NULL, '{}'),
    ('SON-017', cid, 'SON', 'Mea Universal Standardbefestigungsset', 14.49, 14.49, 14.49, NULL, NULL, NULL, '{}'),
    ('SON-018', cid, 'SON', 'Befüllen und Ansähen', 60, 60, 60, NULL, NULL, NULL, '{}'),
    ('SON-019', cid, 'SON', 'Terrrasse Hergestellt', 60, 60, 60, NULL, NULL, NULL, '{}'),
    ('SON-020', cid, 'SON', 'Zusatzarbeit: Treppe gefliest', 60, 60, 60, NULL, NULL, NULL, '{}'),
    ('SON-021', cid, 'SON', 'Abbrucharbeiten', 1200, 1200, 1200, NULL, NULL, NULL, '{}'),
    ('SON-022', cid, 'SON', 'Grabenbefestigung aus Bongossi geflecht 0,4x3m', 8.5, 8.5, 8.5, NULL, NULL, NULL, '{}')
  ON CONFLICT (id) DO NOTHING;
END $$;

SELECT cat, count(*) FROM lv_positions WHERE archived_at IS NULL GROUP BY cat ORDER BY cat;
